export const $characters = [
    {
        id: 1,
        name: "Rick Sanchez",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Male",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: {
            name: "Citadel of Ricks",
            url: "https://rickandmortyapi.com/api/location/3",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/1",
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/3",
            "https://rickandmortyapi.com/api/episode/4",
            "https://rickandmortyapi.com/api/episode/5",
            "https://rickandmortyapi.com/api/episode/6",
            "https://rickandmortyapi.com/api/episode/7",
            "https://rickandmortyapi.com/api/episode/8",
            "https://rickandmortyapi.com/api/episode/9",
            "https://rickandmortyapi.com/api/episode/10",
            "https://rickandmortyapi.com/api/episode/11",
            "https://rickandmortyapi.com/api/episode/12",
            "https://rickandmortyapi.com/api/episode/13",
            "https://rickandmortyapi.com/api/episode/14",
            "https://rickandmortyapi.com/api/episode/15",
            "https://rickandmortyapi.com/api/episode/16",
            "https://rickandmortyapi.com/api/episode/17",
            "https://rickandmortyapi.com/api/episode/18",
            "https://rickandmortyapi.com/api/episode/19",
            "https://rickandmortyapi.com/api/episode/20",
            "https://rickandmortyapi.com/api/episode/21",
            "https://rickandmortyapi.com/api/episode/22",
            "https://rickandmortyapi.com/api/episode/23",
            "https://rickandmortyapi.com/api/episode/24",
            "https://rickandmortyapi.com/api/episode/25",
            "https://rickandmortyapi.com/api/episode/26",
            "https://rickandmortyapi.com/api/episode/27",
            "https://rickandmortyapi.com/api/episode/28",
            "https://rickandmortyapi.com/api/episode/29",
            "https://rickandmortyapi.com/api/episode/30",
            "https://rickandmortyapi.com/api/episode/31",
            "https://rickandmortyapi.com/api/episode/32",
            "https://rickandmortyapi.com/api/episode/33",
            "https://rickandmortyapi.com/api/episode/34",
            "https://rickandmortyapi.com/api/episode/35",
            "https://rickandmortyapi.com/api/episode/36",
            "https://rickandmortyapi.com/api/episode/37",
            "https://rickandmortyapi.com/api/episode/38",
            "https://rickandmortyapi.com/api/episode/39",
            "https://rickandmortyapi.com/api/episode/40",
            "https://rickandmortyapi.com/api/episode/41",
            "https://rickandmortyapi.com/api/episode/42",
            "https://rickandmortyapi.com/api/episode/43",
            "https://rickandmortyapi.com/api/episode/44",
            "https://rickandmortyapi.com/api/episode/45",
            "https://rickandmortyapi.com/api/episode/46",
            "https://rickandmortyapi.com/api/episode/47",
            "https://rickandmortyapi.com/api/episode/48",
            "https://rickandmortyapi.com/api/episode/49",
            "https://rickandmortyapi.com/api/episode/50",
            "https://rickandmortyapi.com/api/episode/51",
        ],
        url: "https://rickandmortyapi.com/api/character/1",
        created: "2017-11-04T18:48:46.250Z",
    },
    {
        id: 38,
        name: "Beth Smith",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Female",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/38.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/1",
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/3",
            "https://rickandmortyapi.com/api/episode/4",
            "https://rickandmortyapi.com/api/episode/5",
            "https://rickandmortyapi.com/api/episode/6",
            "https://rickandmortyapi.com/api/episode/22",
            "https://rickandmortyapi.com/api/episode/51",
        ],
        url: "https://rickandmortyapi.com/api/character/38",
        created: "2017-11-05T09:48:44.230Z",
    },
    {
        id: 175,
        name: "Jerry Smith",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Male",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/175.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/1",
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/3",
            "https://rickandmortyapi.com/api/episode/4",
            "https://rickandmortyapi.com/api/episode/5",
            "https://rickandmortyapi.com/api/episode/6",
            "https://rickandmortyapi.com/api/episode/22",
        ],
        url: "https://rickandmortyapi.com/api/character/175",
        created: "2017-12-29T18:07:17.610Z",
    },
    {
        id: 338,
        name: "Summer Smith",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Female",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/338.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/1",
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/3",
            "https://rickandmortyapi.com/api/episode/4",
            "https://rickandmortyapi.com/api/episode/5",
            "https://rickandmortyapi.com/api/episode/6",
            "https://rickandmortyapi.com/api/episode/22",
        ],
        url: "https://rickandmortyapi.com/api/character/338",
        created: "2018-01-10T16:55:03.390Z",
    },
    {
        id: 405,
        name: "Trunkphobic suspenders guy",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Male",
        origin: { name: "unknown", url: "" },
        location: {
            name: "Earth (Replacement Dimension)",
            url: "https://rickandmortyapi.com/api/location/20",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/405.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/8",
            "https://rickandmortyapi.com/api/episode/10",
            "https://rickandmortyapi.com/api/episode/11",
        ],
        url: "https://rickandmortyapi.com/api/character/405",
        created: "2018-04-15T20:31:46.065Z",
    },
    {
        id: 2,
        name: "Morty Smith",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Male",
        origin: { name: "unknown", url: "" },
        location: {
            name: "Citadel of Ricks",
            url: "https://rickandmortyapi.com/api/location/3",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/1",
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/3",
            "https://rickandmortyapi.com/api/episode/4",
            "https://rickandmortyapi.com/api/episode/5",
            "https://rickandmortyapi.com/api/episode/6",
            "https://rickandmortyapi.com/api/episode/7",
            "https://rickandmortyapi.com/api/episode/8",
            "https://rickandmortyapi.com/api/episode/9",
            "https://rickandmortyapi.com/api/episode/10",
            "https://rickandmortyapi.com/api/episode/11",
            "https://rickandmortyapi.com/api/episode/12",
            "https://rickandmortyapi.com/api/episode/13",
            "https://rickandmortyapi.com/api/episode/14",
            "https://rickandmortyapi.com/api/episode/15",
            "https://rickandmortyapi.com/api/episode/16",
            "https://rickandmortyapi.com/api/episode/17",
            "https://rickandmortyapi.com/api/episode/18",
            "https://rickandmortyapi.com/api/episode/19",
            "https://rickandmortyapi.com/api/episode/20",
            "https://rickandmortyapi.com/api/episode/21",
            "https://rickandmortyapi.com/api/episode/22",
            "https://rickandmortyapi.com/api/episode/23",
            "https://rickandmortyapi.com/api/episode/24",
            "https://rickandmortyapi.com/api/episode/25",
            "https://rickandmortyapi.com/api/episode/26",
            "https://rickandmortyapi.com/api/episode/27",
            "https://rickandmortyapi.com/api/episode/28",
            "https://rickandmortyapi.com/api/episode/29",
            "https://rickandmortyapi.com/api/episode/30",
            "https://rickandmortyapi.com/api/episode/31",
            "https://rickandmortyapi.com/api/episode/32",
            "https://rickandmortyapi.com/api/episode/33",
            "https://rickandmortyapi.com/api/episode/34",
            "https://rickandmortyapi.com/api/episode/35",
            "https://rickandmortyapi.com/api/episode/36",
            "https://rickandmortyapi.com/api/episode/37",
            "https://rickandmortyapi.com/api/episode/38",
            "https://rickandmortyapi.com/api/episode/39",
            "https://rickandmortyapi.com/api/episode/40",
            "https://rickandmortyapi.com/api/episode/41",
            "https://rickandmortyapi.com/api/episode/42",
            "https://rickandmortyapi.com/api/episode/43",
            "https://rickandmortyapi.com/api/episode/44",
            "https://rickandmortyapi.com/api/episode/45",
            "https://rickandmortyapi.com/api/episode/46",
            "https://rickandmortyapi.com/api/episode/47",
            "https://rickandmortyapi.com/api/episode/48",
            "https://rickandmortyapi.com/api/episode/49",
            "https://rickandmortyapi.com/api/episode/50",
            "https://rickandmortyapi.com/api/episode/51",
        ],
        url: "https://rickandmortyapi.com/api/character/2",
        created: "2017-11-04T18:50:21.651Z",
    },
    {
        id: 239,
        name: "Mr. Goldenfold",
        status: "Alive",
        species: "Cronenberg",
        type: "",
        gender: "Male",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/239.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/1",
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/4",
            "https://rickandmortyapi.com/api/episode/6",
        ],
        url: "https://rickandmortyapi.com/api/character/239",
        created: "2017-12-30T17:42:11.894Z",
    },
    {
        id: 80,
        name: "Creepy Little Girl",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Female",
        origin: { name: "unknown", url: "" },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/80.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/80",
        created: "2017-11-30T14:20:35.772Z",
    },
    {
        id: 63,
        name: "Centaur",
        status: "Alive",
        species: "Mythological Creature",
        type: "Centaur",
        gender: "Male",
        origin: { name: "unknown", url: "" },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/63.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/63",
        created: "2017-11-05T12:22:17.848Z",
    },
    {
        id: 304,
        name: "Scary Brandon",
        status: "Alive",
        species: "Mythological Creature",
        type: "Monster",
        gender: "Male",
        origin: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/304.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/304",
        created: "2018-01-05T14:11:17.550Z",
    },
    {
        id: 46,
        name: "Bill",
        status: "unknown",
        species: "Animal",
        type: "Dog",
        gender: "Male",
        origin: {
            name: "Earth (Replacement Dimension)",
            url: "https://rickandmortyapi.com/api/location/20",
        },
        location: { name: "unknown", url: "" },
        image: "https://rickandmortyapi.com/api/character/avatar/46.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/46",
        created: "2017-11-05T10:24:38.089Z",
    },
    {
        id: 305,
        name: "Scary Glenn",
        status: "Alive",
        species: "Mythological Creature",
        type: "Monster",
        gender: "Male",
        origin: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/305.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/305",
        created: "2018-01-05T14:11:53.287Z",
    },
    {
        id: 329,
        name: "Snuffles (Snowball)",
        status: "Alive",
        species: "Animal",
        type: "Dog",
        gender: "Male",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: { name: "unknown", url: "" },
        image: "https://rickandmortyapi.com/api/character/avatar/329.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/7",
            "https://rickandmortyapi.com/api/episode/10",
            "https://rickandmortyapi.com/api/episode/15",
            "https://rickandmortyapi.com/api/episode/16",
            "https://rickandmortyapi.com/api/episode/24",
            "https://rickandmortyapi.com/api/episode/29",
            "https://rickandmortyapi.com/api/episode/30",
        ],
        url: "https://rickandmortyapi.com/api/character/329",
        created: "2018-01-10T16:24:49.586Z",
    },
    {
        id: 396,
        name: "Scary Teacher",
        status: "Alive",
        species: "Mythological Creature",
        type: "Monster",
        gender: "Male",
        origin: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/396.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/396",
        created: "2018-04-15T17:10:07.639Z",
    },
    {
        id: 221,
        name: "Melissa",
        status: "Alive",
        species: "Mythological Creature",
        type: "Monster",
        gender: "Female",
        origin: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/221.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/221",
        created: "2017-12-30T14:38:04.718Z",
    },
    {
        id: 397,
        name: "Fido",
        status: "Alive",
        species: "Animal",
        type: "Dog",
        gender: "Male",
        origin: {
            name: "Snuffles' Dream",
            url: "https://rickandmortyapi.com/api/location/70",
        },
        location: {
            name: "Snuffles' Dream",
            url: "https://rickandmortyapi.com/api/location/70",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/397.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/397",
        created: "2018-04-15T17:15:28.777Z",
    },
    {
        id: 398,
        name: "Accountant dog",
        status: "Alive",
        species: "Animal",
        type: "Dog",
        gender: "Male",
        origin: {
            name: "Snuffles' Dream",
            url: "https://rickandmortyapi.com/api/location/70",
        },
        location: {
            name: "Snuffles' Dream",
            url: "https://rickandmortyapi.com/api/location/70",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/398.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/398",
        created: "2018-04-15T17:23:04.169Z",
    },
    {
        id: 246,
        name: "Mrs. Pancakes",
        status: "Alive",
        species: "Human",
        type: "",
        gender: "Female",
        origin: {
            name: "Earth (C-137)",
            url: "https://rickandmortyapi.com/api/location/1",
        },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/246.jpeg",
        episode: [
            "https://rickandmortyapi.com/api/episode/2",
            "https://rickandmortyapi.com/api/episode/27",
        ],
        url: "https://rickandmortyapi.com/api/character/246",
        created: "2017-12-30T18:09:39.304Z",
    },
    {
        id: 306,
        name: "Scary Terry",
        status: "Alive",
        species: "Mythological Creature",
        type: "Monster",
        gender: "Male",
        origin: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        location: {
            name: "Mr. Goldenfold's dream",
            url: "https://rickandmortyapi.com/api/location/18",
        },
        image: "https://rickandmortyapi.com/api/character/avatar/306.jpeg",
        episode: ["https://rickandmortyapi.com/api/episode/2"],
        url: "https://rickandmortyapi.com/api/character/306",
        created: "2018-01-05T14:13:01.564Z",
    },
];
